spring.application.name=smartPos
# Database connection settings
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/xe
spring.datasource.username=system
spring.datasource.password=12345678
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.schema=classpath:schema.sql
spring.datasource.data=classpath:data.sql

# Disable Hibernate SQL logs
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF


# Hibernate settings
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.Oracle12cDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_temporary_tables=false

