spring.application.name=smartPos
# Database connection settings
spring.datasource.url=jdbc:mysql://pos-test.mysql.database.azure.com:3306/smartpos?serverTimezone=UTC&useSSL=true&requireSSL=true
spring.datasource.username=SMARTPOS
spring.datasource.password=Sasindu108$
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.schema=classpath:schema.sql
#spring.datasource.data=classpath:data.sql
spring.datasource.hikari.connection-timeout=30000


# Hibernate settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CORS allowed origin
app.cors.allowed-origin=https://posangular-dsd7emhsgjema8c0.australiacentral-01.azurewebsites.net

